"""
varco_fastapi.client.base
===========================
``ClientProfile``, ``AsyncVarcoClient[R]``, and ``_VarcoClientMeta`` metaclass.

Architecture overview::

    ClientProfile        — reusable bundle of middleware / TLS / timeout config
    ClientConfigurator   — per-service URL / proxy / env config (in configurator.py)
    _VarcoClientMeta     — metaclass: generates typed CRUD methods at class-definition
    AsyncVarcoClient[R]  — concrete httpx-backed client; metaclass applies to it
    SyncVarcoClient      — sync wrapper (in sync.py), created via .sync property

The metaclass pattern mirrors ``AsyncService``'s ``__init_subclass__`` approach for
resolving generic type parameters, but uses ``__new__`` (metaclass) because we need
to *inject methods*, not just record metadata.

DESIGN: metaclass method generation over @overload stubs
    ✅ Methods exist at runtime — no stubs required for basic usage
    ✅ IDE stubs can still be generated by StubGenerator for autocomplete
    ✅ Same router introspection used by build_router() — single source of truth
    ✅ Methods generated once per class — no per-instance overhead
    ❌ Metaclass adds complexity — mitigated by confining it to _VarcoClientMeta

DESIGN: frozen ClientProfile over mutable client config
    ✅ Safe to share across multiple client instances and services
    ✅ with_middleware() / with_timeout() return new profiles (immutable builders)
    ✅ Factory methods (production, development, from_env) cover 90% of use cases
    ❌ Appending middleware requires with_middleware() — no in-place mutation

Thread safety:  ✅ ClientProfile is frozen — safe to share across threads.
                ✅ _VarcoClientMeta is called once at class-definition; no shared state.
Async safety:   ✅ AsyncVarcoClient creates a fresh httpx.AsyncClient per instance;
                   no shared mutable state between concurrent callers.
"""

from __future__ import annotations

import dataclasses
import json
import os
import typing
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, ClassVar, Generic, TypeVar

import httpx

if TYPE_CHECKING:
    from varco_fastapi.auth.trust_store import TrustStore
    from varco_fastapi.client.configurator import ClientConfigurator
    from varco_fastapi.client.middleware import (
        AbstractClientMiddleware,
        PreparedRequest,
    )
    from varco_fastapi.client.sync import SyncVarcoClient

R = TypeVar("R")


# ── ClientProfile ─────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class ClientProfile:
    """
    Reusable bundle of client middleware, TLS trust store, and timeout.

    Shared across multiple ``AsyncVarcoClient`` instances — frozen so it is
    safe to share across threads and services.

    Three factory methods cover the common cases:

    1. ``production()`` — OTel tracing + JWT auth + correlation + retry.
    2. ``development()`` — logging + correlation only (no auth / TLS).
    3. ``from_env()`` — reads ``VARCO_CLIENT_TIMEOUT``, ``VARCO_CLIENT_RETRY_MAX``,
       ``VARCO_CLIENT_RETRY_DELAY``, ``VARCO_CLIENT_OTEL_ENABLED``.

    Immutable builders::

        prod = ClientProfile.production(authority=my_authority)
        with_extra = prod.with_middleware(HeadersMiddleware({"X-Service": "api"}))
        fast = prod.with_timeout(5.0)

    Args:
        middleware:   Tuple of ``AbstractClientMiddleware`` instances applied in order.
        trust_store:  ``TrustStore`` for TLS CA / mTLS config.  ``None`` = system CAs.
        timeout:      Default request timeout in seconds.

    Thread safety:  ✅ frozen=True — safe to share across threads / services.
    Async safety:   ✅ Pure data object; no I/O.

    Edge cases:
        - Empty middleware tuple → no middleware applied (direct httpx call).
        - trust_store=None → system CA bundle used by httpx by default.
    """

    middleware: tuple[AbstractClientMiddleware, ...] = ()
    trust_store: TrustStore | None = None
    timeout: float = 30.0

    @classmethod
    def production(
        cls,
        *,
        authority: Any | None = None,
        audience: str = "api",
        retry_policy: Any | None = None,
        trust_store: TrustStore | None = None,
        timeout: float = 30.0,
    ) -> ClientProfile:
        """
        Production-ready profile.

        Builds middleware stack::

            OTelClientMiddleware → JwtMiddleware (if authority)
            → CorrelationIdMiddleware → RetryMiddleware (if retry_policy)

        Args:
            authority:     ``JwtAuthority`` for signing outbound JWTs.  ``None``
                           means no JWT middleware is added.
            audience:      JWT ``aud`` claim (default ``"api"``).
            retry_policy:  ``RetryPolicy`` for ``RetryMiddleware``.  ``None``
                           means no retry is applied.
            trust_store:   TLS trust config.  ``None`` = system CAs.
            timeout:       Request timeout in seconds.

        Returns:
            Frozen ``ClientProfile`` suitable for production deployments.
        """
        from varco_fastapi.client.middleware import (  # noqa: PLC0415
            CorrelationIdMiddleware,
            JwtMiddleware,
            OTelClientMiddleware,
            RetryMiddleware,
        )

        mw: list[AbstractClientMiddleware] = [
            OTelClientMiddleware(),
            CorrelationIdMiddleware(),
        ]

        if authority is not None:
            mw.append(
                JwtMiddleware(
                    authority,
                    audience=audience,
                    expires_in=3600,
                )
            )

        if retry_policy is not None:
            mw.append(RetryMiddleware(retry_policy))

        return cls(middleware=tuple(mw), trust_store=trust_store, timeout=timeout)

    @classmethod
    def development(cls, *, timeout: float = 10.0) -> ClientProfile:
        """
        Lightweight profile for local development.

        Adds only logging and correlation ID propagation.  No auth, no TLS,
        no retry — fast feedback loop.

        Args:
            timeout: Request timeout in seconds (default 10.0).

        Returns:
            Frozen ``ClientProfile`` for local development.
        """
        from varco_fastapi.client.middleware import (  # noqa: PLC0415
            CorrelationIdMiddleware,
            LoggingMiddleware,
        )

        return cls(
            middleware=(LoggingMiddleware(), CorrelationIdMiddleware()),
            timeout=timeout,
        )

    @classmethod
    def from_env(cls) -> ClientProfile:
        """
        Read middleware config from environment variables.

        Env vars::

            VARCO_CLIENT_TIMEOUT       — default timeout in seconds (default: 30)
            VARCO_CLIENT_RETRY_MAX     — max retry attempts (0 = disabled; default: 0)
            VARCO_CLIENT_RETRY_DELAY   — base retry delay in seconds (default: 0.5)
            VARCO_CLIENT_OTEL_ENABLED  — "true"/"false" (default: "true")

        JWT authority is NOT read from env — private keys must be passed explicitly.

        Returns:
            Frozen ``ClientProfile`` configured from environment.

        Edge cases:
            - Unknown env var values → logged and defaults used.
            - ``VARCO_CLIENT_RETRY_MAX=0`` → no retry middleware added.
        """
        from varco_fastapi.client.middleware import (  # noqa: PLC0415
            CorrelationIdMiddleware,
            OTelClientMiddleware,
            RetryMiddleware,
        )
        from varco_core.resilience import RetryPolicy  # noqa: PLC0415

        timeout = float(os.environ.get("VARCO_CLIENT_TIMEOUT", "30"))
        retry_max = int(os.environ.get("VARCO_CLIENT_RETRY_MAX", "0"))
        retry_delay = float(os.environ.get("VARCO_CLIENT_RETRY_DELAY", "0.5"))
        otel_enabled = (
            os.environ.get("VARCO_CLIENT_OTEL_ENABLED", "true").lower() == "true"
        )

        mw: list[AbstractClientMiddleware] = []
        if otel_enabled:
            mw.append(OTelClientMiddleware())
        mw.append(CorrelationIdMiddleware())
        if retry_max > 0:
            mw.append(
                RetryMiddleware(
                    RetryPolicy(max_attempts=retry_max, base_delay=retry_delay)
                )
            )

        return cls(middleware=tuple(mw), timeout=timeout)

    def with_middleware(self, *mw: AbstractClientMiddleware) -> ClientProfile:
        """
        Return new profile with additional middleware appended.

        Args:
            *mw: Middleware instances to append.

        Returns:
            New ``ClientProfile`` with appended middleware.
        """
        # dataclasses.replace creates a new frozen instance with the updated field
        return dataclasses.replace(self, middleware=self.middleware + mw)

    def with_timeout(self, timeout: float) -> ClientProfile:
        """
        Return new profile with overridden timeout.

        Args:
            timeout: New timeout in seconds.

        Returns:
            New ``ClientProfile`` with updated timeout.
        """
        return dataclasses.replace(self, timeout=timeout)

    def with_trust_store(self, trust_store: TrustStore) -> ClientProfile:
        """
        Return new profile with overridden TLS trust store.

        Args:
            trust_store: ``TrustStore`` for CA / mTLS config.

        Returns:
            New ``ClientProfile`` with updated trust store.
        """
        return dataclasses.replace(self, trust_store=trust_store)


# ── _VarcoClientMeta ───────────────────────────────────────────────────────────


class _VarcoClientMeta(type):
    """
    Metaclass for ``AsyncVarcoClient``.

    Runs at class-definition time to:

    1. Walk ``cls.__orig_bases__`` for ``AsyncVarcoClient[SomeRouter]``.
    2. Extract ``SomeRouter`` via ``typing.get_args()``.
    3. Introspect routes from ``SomeRouter`` via ``introspect_routes()``.
    4. Generate typed async CRUD methods (``create``, ``read``, ``update``,
       ``patch``, ``delete``, ``list``) plus methods for ``@route`` custom endpoints.

    Generated method signatures match the router's type parameters.  A
    ``StubGenerator`` can produce ``.pyi`` stubs for IDE autocomplete.

    DESIGN: metaclass ``__new__`` over ``__init_subclass__``
        ✅ Can inject methods onto the new class before it is returned
        ✅ ``__init_subclass__`` cannot modify the class's ``__dict__``
        ❌ Metaclass syntax is more complex — mitigated by isolating it here

    Thread safety:  ✅ Called once per class; no shared mutable state after that.
    Async safety:   ✅ No I/O; introspection is synchronous.

    Edge cases:
        - ``AsyncVarcoClient`` itself → skipped (no router param).
        - Intermediate base class without ``[R]`` param → skipped.
        - Router with no CRUD mixins → no CRUD methods generated; custom
          ``@route`` methods still generated.
        - Type args contain TypeVars (abstract subclass) → skipped cleanly.
    """

    def __new__(
        mcs,
        name: str,
        bases: tuple[type, ...],
        namespace: dict[str, Any],
        **kwargs: Any,
    ) -> type:
        cls = super().__new__(mcs, name, bases, namespace, **kwargs)

        # Skip the base class itself — it has no router type to resolve
        if name == "AsyncVarcoClient":
            return cls

        # Resolve R from Generic[R] via __orig_bases__
        router_cls = mcs._resolve_router_type(cls)
        if router_cls is not None:
            # Store on class so it can be accessed later (e.g. by bind_clients())
            cls._router_class = router_cls
            # Generate methods based on the router's routes
            mcs._inject_crud_methods(cls, router_cls)

        return cls

    @staticmethod
    def _resolve_router_type(cls: type) -> type | None:
        """
        Walk ``__orig_bases__`` to find ``AsyncVarcoClient[SomeRouter]``.

        Returns ``SomeRouter`` type or ``None`` if this is an intermediate
        base class without a concrete router type parameter.

        Args:
            cls: The newly defined class.

        Returns:
            The ``VarcoRouter`` subclass or ``None``.

        Edge cases:
            - TypeVar in args (abstract subclass) → returns ``None``.
            - Multiple generic bases → first ``AsyncVarcoClient[R]`` wins.
        """
        for base in getattr(cls, "__orig_bases__", ()):
            origin = typing.get_origin(base)
            if origin is None:
                continue
            # Check if the origin is AsyncVarcoClient (by name to avoid import cycle)
            if not (isinstance(origin, type) and origin.__name__ == "AsyncVarcoClient"):
                continue
            args = typing.get_args(base)
            if not args:
                continue
            arg = args[0]
            # Skip TypeVars — this is an abstract intermediate class
            if isinstance(arg, TypeVar):
                continue
            # Import here to avoid circular dependency at module level
            try:
                from varco_fastapi.router.base import VarcoRouter  # noqa: PLC0415

                if isinstance(arg, type) and issubclass(arg, VarcoRouter):
                    return arg
            except ImportError:
                pass
        # Also check explicit _router_class ClassVar set by parent class
        return getattr(cls, "_router_class", None)

    @staticmethod
    def _inject_crud_methods(cls: type, router_cls: type) -> None:
        """
        Generate and inject typed async methods onto ``cls``.

        Each generated method calls ``self._request(...)`` with the right
        HTTP method, path, body model, and response model.

        Args:
            cls:        The client class to inject methods onto.
            router_cls: The router class to introspect.

        Edge cases:
            - Methods already defined on ``cls`` (explicit overrides) → skipped.
            - Router with no CRUD mixins → no CRUD methods injected.
            - Custom ``@route`` methods → one generated method per route.
        """
        try:
            from varco_fastapi.router.introspection import (
                introspect_routes,
            )  # noqa: PLC0415
        except ImportError:
            return

        # Resolve type args for request/response model typing
        type_args = _resolve_router_type_args(router_cls)

        routes = introspect_routes(router_cls, type_args=type_args)

        for route in routes:
            # Skip WS/SSE routes — not HTTP request/response
            if route.method in ("WS",):
                continue
            # Skip if method already defined (explicit override wins)
            if route.name in cls.__dict__:
                continue

            # Generate the method closure for this route
            method_fn = _make_client_method(route)
            setattr(cls, route.name, method_fn)


def _resolve_router_type_args(router_cls: type) -> tuple[type, ...] | None:
    """
    Extract ``(D, PK, C, R, U)`` from ``router_cls.__orig_bases__``.

    Args:
        router_cls: The ``VarcoRouter`` subclass.

    Returns:
        Tuple of resolved type args or ``None`` if not parameterized.
    """
    try:
        from varco_fastapi.router.base import VarcoRouter  # noqa: PLC0415
    except ImportError:
        return None

    for base in getattr(router_cls, "__orig_bases__", ()):
        origin = typing.get_origin(base)
        if origin is None:
            continue
        if not (isinstance(origin, type) and issubclass(origin, VarcoRouter)):
            continue
        args = typing.get_args(base)
        # Filter out TypeVars — only return if we have concrete types
        if args and not any(isinstance(a, TypeVar) for a in args):
            return tuple(args)
    return None


def _make_client_method(route: Any) -> Any:
    """
    Build a typed async method closure for a single ``ResolvedRoute``.

    The closure captures ``route`` at definition time — no late-binding issues.

    Args:
        route: The ``ResolvedRoute`` describing the endpoint.

    Returns:
        An async function that calls ``self._request(...)`` with the right args.

    Edge cases:
        - ``list`` route → wraps query params into ``HttpQueryParams``-compatible
          kwargs and passes as query string.
        - ``create`` / ``update`` / ``patch`` → serializes Pydantic body to JSON bytes.
        - ``delete`` → no body; expects 204 (returns ``None``).
        - Routes with path params → extracted from kwargs by name.
    """
    method_http = route.method
    path = route.path
    crud_action = route.crud_action
    response_model = route.response_model
    status_code = route.status_code

    if crud_action == "create":

        async def create(self: Any, body: Any, *, with_async: bool = False) -> Any:
            """Call the create endpoint (POST /)."""
            return await self._request(
                method_http,
                path,
                body=body,
                path_params={},
                query_params={"with_async": "true"} if with_async else {},
                response_model=response_model,
                expected_status=status_code,
            )

        create.__name__ = "create"
        return create

    elif crud_action == "read":

        async def read(self: Any, pk: Any) -> Any:
            """Call the read endpoint (GET /{id})."""
            return await self._request(
                method_http,
                path,
                body=None,
                path_params={"id": pk},
                query_params={},
                response_model=response_model,
                expected_status=status_code,
            )

        read.__name__ = "read"
        return read

    elif crud_action == "update":

        async def update(self: Any, pk: Any, body: Any) -> Any:
            """Call the update endpoint (PUT /{id})."""
            return await self._request(
                method_http,
                path,
                body=body,
                path_params={"id": pk},
                query_params={},
                response_model=response_model,
                expected_status=status_code,
            )

        update.__name__ = "update"
        return update

    elif crud_action == "patch":

        async def patch(self: Any, pk: Any, body: Any) -> Any:
            """Call the patch endpoint (PATCH /{id})."""
            return await self._request(
                method_http,
                path,
                body=body,
                path_params={"id": pk},
                query_params={},
                response_model=response_model,
                expected_status=status_code,
            )

        patch.__name__ = "patch"
        return patch

    elif crud_action == "delete":

        async def delete(self: Any, pk: Any) -> None:
            """Call the delete endpoint (DELETE /{id})."""
            await self._request(
                method_http,
                path,
                body=None,
                path_params={"id": pk},
                query_params={},
                response_model=None,
                expected_status=status_code,
            )

        delete.__name__ = "delete"
        return delete

    elif crud_action == "list":

        async def list_method(
            self: Any,
            *,
            q: str | None = None,
            sort: str | None = None,
            limit: int | None = None,
            offset: int | None = None,
        ) -> Any:
            """Call the list endpoint (GET /)."""
            qp: dict[str, str] = {}
            if q is not None:
                qp["q"] = q
            if sort is not None:
                qp["sort"] = sort
            if limit is not None:
                qp["limit"] = str(limit)
            if offset is not None:
                qp["offset"] = str(offset)
            return await self._request(
                method_http,
                path,
                body=None,
                path_params={},
                query_params=qp,
                response_model=response_model,
                expected_status=status_code,
            )

        list_method.__name__ = "list"
        return list_method

    else:
        # Custom @route endpoint — extract path params dynamically
        path_params_names = route.path_params

        async def custom_method(self: Any, **kwargs: Any) -> Any:
            """Call a custom @route endpoint."""
            path_params = {k: kwargs.pop(k) for k in path_params_names if k in kwargs}
            query_params = {k: str(v) for k, v in kwargs.items() if v is not None}
            body = kwargs.get("body")
            return await self._request(
                method_http,
                path,
                body=body,
                path_params=path_params,
                query_params=query_params,
                response_model=response_model,
                expected_status=status_code,
            )

        custom_method.__name__ = route.name
        return custom_method


# ── AsyncVarcoClient ──────────────────────────────────────────────────────────


class AsyncVarcoClient(Generic[R], metaclass=_VarcoClientMeta):
    """
    HTTP client that mirrors a ``VarcoRouter``'s endpoints as typed async methods.

    The metaclass reads the router type ``R`` from the generic parameter at
    class-definition time and generates typed CRUD methods (``create``, ``read``,
    ``update``, ``patch``, ``delete``, ``list``) plus methods for any
    ``@route``-decorated custom endpoints on the router.

    Configuration layers (highest priority first):

    1. Constructor kwargs (``base_url``, ``middleware``, ``timeout``)
    2. Per-instance ``configurator`` kwarg
    3. Class-level ``_configurator`` ClassVar
    4. Class-level ``_profile`` ClassVar
    5. Defaults (no middleware, system CAs, 30s timeout)

    Usage::

        # Zero-URL instantiation via configurator
        class OrderClient(AsyncVarcoClient[OrderRouter]):
            _configurator = OrderConfigurator

        async with OrderClient() as client:
            order = await client.create(CreateOrderDTO(name="test"))
            page = await client.list(q="status = 'active'", limit=20)

        # Explicit URL
        async with AsyncVarcoClient[OrderRouter]("https://api.example.com") as client:
            order = await client.read(order_id)

    Type parameter:
        R: ``VarcoRouter`` subclass.  Resolved at class-definition time.

    Thread safety:  ✅ Each instance has its own ``httpx.AsyncClient``.
    Async safety:   ✅ httpx is fully async; concurrent calls are safe within
                       one instance when using async context manager.

    Edge cases:
        - No ``base_url`` and no configurator → ``RuntimeError`` at first request.
        - ``with_async=True`` on methods → returns raw dict (``JobAcceptedResponse``).
        - Pydantic ``response_model=None`` (delete) → returns ``None`` directly.
    """

    # Set by metaclass when class is parameterized with a VarcoRouter
    _router_class: ClassVar[type | None] = None
    # Class-level configurator — used for zero-URL instantiation
    _configurator: ClassVar[type[ClientConfigurator] | None] = None
    # Class-level profile default
    _profile: ClassVar[ClientProfile | None] = None

    def __init__(
        self,
        base_url: str | None = None,
        *,
        configurator: ClientConfigurator | None = None,
        profile: ClientProfile | None = None,
        middleware: tuple[AbstractClientMiddleware, ...] | None = None,
        trust_store: TrustStore | None = None,
        timeout: float | None = None,
    ) -> None:
        """
        Args:
            base_url:     Explicit base URL.  Overrides configurator and env vars.
            configurator: Per-instance configurator for URL / proxy / headers.
            profile:      Per-instance profile (middleware / TLS / timeout).
            middleware:   Extra middleware appended to the profile's stack.
            trust_store:  TLS trust config override.
            timeout:      Timeout override in seconds.

        Edge cases:
            - ``base_url`` is required unless configurator provides a URL.
            - ``middleware`` tuple is appended to, not replacing, profile middleware.
        """
        # Resolve configurator: per-instance > class-level
        _configurator = configurator or (
            type(self)._configurator() if type(self)._configurator else None
        )

        # Resolve base URL: explicit > configurator.get_url()
        if base_url:
            self._base_url: str = base_url
        elif _configurator is not None:
            self._base_url = _configurator.get_url()
        else:
            # No URL — will raise on first _request() call
            self._base_url = ""

        # Resolve profile: explicit kwarg > configurator.profile() > class _profile > default
        resolved_profile: ClientProfile
        if profile is not None:
            resolved_profile = profile
        elif _configurator is not None:
            resolved_profile = _configurator.profile()
        elif type(self)._profile is not None:
            resolved_profile = type(self)._profile
        else:
            resolved_profile = ClientProfile()

        # Apply per-instance overrides on top of resolved profile
        if middleware:
            resolved_profile = resolved_profile.with_middleware(*middleware)
        if trust_store is not None:
            resolved_profile = resolved_profile.with_trust_store(trust_store)
        if timeout is not None:
            resolved_profile = resolved_profile.with_timeout(timeout)

        self._resolved_profile = resolved_profile
        self._proxy_url: str | None = (
            _configurator.get_proxy() if _configurator else None
        )

        # httpx.AsyncClient is created lazily (or in __aenter__)
        self._client: httpx.AsyncClient | None = None

    async def __aenter__(self) -> AsyncVarcoClient[R]:
        """Open the underlying httpx.AsyncClient."""
        self._client = self._build_httpx_client()
        await self._client.__aenter__()
        return self

    async def __aexit__(self, *exc: Any) -> None:
        """Close the underlying httpx.AsyncClient."""
        if self._client is not None:
            await self._client.__aexit__(*exc)
            self._client = None

    def _build_httpx_client(self) -> httpx.AsyncClient:
        """
        Construct the ``httpx.AsyncClient`` with resolved config.

        Returns:
            Configured ``httpx.AsyncClient`` instance.
        """
        kwargs: dict[str, Any] = {
            "base_url": self._base_url,
            "timeout": self._resolved_profile.timeout,
        }
        if self._proxy_url:
            kwargs["proxy"] = self._proxy_url
        if self._resolved_profile.trust_store is not None:
            kwargs["verify"] = self._resolved_profile.trust_store.build_ssl_context()
        return httpx.AsyncClient(**kwargs)

    async def _request(
        self,
        method: str,
        path: str,
        *,
        body: Any = None,
        path_params: dict[str, Any] | None = None,
        query_params: dict[str, str] | None = None,
        response_model: type | None = None,
        expected_status: int = 200,
    ) -> Any:
        """
        Execute an HTTP request through the middleware pipeline.

        Args:
            method:          HTTP method (``"GET"``, ``"POST"``, etc.).
            path:            URL path template (e.g. ``"/{id}"``).
            body:            Request body — Pydantic model or plain dict.
            path_params:     Dict of ``{param: value}`` to substitute in path.
            query_params:    Dict of query string parameters.
            response_model:  Pydantic model class to deserialize the response body.
                             ``None`` for 204 No Content responses.
            expected_status: Expected HTTP status code; raises on mismatch.

        Returns:
            Deserialized response (Pydantic model instance, dict, or ``None``).

        Raises:
            RuntimeError:    No base URL configured.
            httpx.HTTPStatusError: Response status did not match ``expected_status``.

        Edge cases:
            - ``body`` is a Pydantic ``BaseModel`` → serialized with ``model_dump()``.
            - ``response_model=None`` and 204 → returns ``None``.
            - Middleware pipeline is empty → request goes directly to httpx.
        """
        if not self._base_url:
            raise RuntimeError(
                f"{type(self).__name__} has no base URL configured. "
                "Pass base_url to the constructor or set a _configurator ClassVar."
            )

        # Build the effective URL path (substitute path params)
        effective_path = path
        for key, value in (path_params or {}).items():
            effective_path = effective_path.replace(f"{{{key}}}", str(value))

        # Serialize body to JSON bytes
        raw_body: bytes | None = None
        if body is not None:
            # Pydantic model → dict → JSON; plain dict → JSON directly
            try:
                raw_body = body.model_dump_json(exclude_unset=True).encode()
            except AttributeError:
                raw_body = json.dumps(body).encode()

        # Build PreparedRequest for the middleware pipeline
        from varco_fastapi.client.middleware import PreparedRequest  # noqa: PLC0415

        headers: dict[str, str] = {}
        if raw_body is not None:
            headers["Content-Type"] = "application/json"

        prepared = PreparedRequest(
            method=method,
            url=effective_path,
            headers=headers,
            body=raw_body,
            query_params=query_params or {},
        )

        # Run middleware pipeline then call httpx
        response = await self._run_pipeline(prepared)

        # Validate status
        response.raise_for_status()

        # Deserialize response
        if response_model is None or response.status_code == 204:
            return None

        data = response.json()
        # Pydantic model deserialization
        try:
            return response_model.model_validate(data)
        except AttributeError:
            # Not a Pydantic model — return raw dict
            return data

    async def _run_pipeline(self, request: PreparedRequest) -> httpx.Response:
        """
        Run the middleware stack and execute the request.

        Middleware wraps each other left-to-right; the innermost function
        calls the actual httpx client.

        Args:
            request: The ``PreparedRequest`` to execute.

        Returns:
            The ``httpx.Response`` from httpx.

        Edge cases:
            - Empty middleware → calls httpx directly.
            - Lazy client creation if called outside context manager.
        """

        middleware = self._resolved_profile.middleware

        async def _call_httpx(req: PreparedRequest) -> httpx.Response:
            """Innermost handler: call the real httpx.AsyncClient."""
            client = self._client or self._build_httpx_client()
            return await client.request(
                method=req.method,
                url=req.url,
                headers=req.headers,
                content=req.body,
                params=req.query_params,
            )

        # Build nested pipeline: mw[-1](mw[-2](... mw[0](_call_httpx) ...))
        handler = _call_httpx
        for mw in reversed(middleware):
            # Capture mw and next_handler in closure to avoid late-binding
            _mw = mw
            _next = handler

            async def make_next(
                req: PreparedRequest, __mw: Any = _mw, __next: Any = _next
            ) -> httpx.Response:
                return await __mw(req, __next)

            handler = make_next

        return await handler(request)

    @property
    def sync(self) -> SyncVarcoClient:
        """
        Return a synchronous wrapper around this client's configuration.

        The sync client shares the same ``base_url``, ``profile``, and proxy
        settings.  Use it in blocking contexts (CLI scripts, WSGI apps).

        Returns:
            ``SyncVarcoClient`` wrapping this async client.

        Edge cases:
            - ``with_async=True`` on any sync method raises ``SyncClientAsyncError``.
        """
        from varco_fastapi.client.sync import SyncVarcoClient  # noqa: PLC0415

        return SyncVarcoClient(self)

    def __repr__(self) -> str:
        """Return a concise string representation for debugging."""
        router_name = (
            getattr(self._router_class, "__name__", "?") if self._router_class else "?"
        )
        return (
            f"{type(self).__name__}("
            f"router={router_name}, "
            f"url={self._base_url!r})"
        )


# Public alias — VarcoClient[R] works identically to AsyncVarcoClient[R]
VarcoClient = AsyncVarcoClient


__all__ = [
    "ClientProfile",
    "AsyncVarcoClient",
    "VarcoClient",
]
