"""
example.models
==============
Domain model for the Post entity.

``Post`` is a pure-Python ``@dataclass`` — no ORM imports, no session
references.  The SQLAlchemy backend (``varco_sa``) generates the ORM
mapping at import time via ``SAModelFactory`` from the field annotations
and ``FieldHint`` / ``PrimaryKey`` metadata.

Design choices:
    ``pk`` uses ``PKStrategy.UUID_AUTO`` — the repository generates a UUID
    before INSERT so the ``pk`` is available immediately after ``save()``.

    ``author_id`` is intentionally absent from ``PostCreate`` DTO — it is
    stamped from ``AuthContext.subject`` in ``PostService._prepare_for_create``
    so users can never forge their own author identity.

Thread safety:  ✅ Immutable after creation (frozen-dataclass semantics via
                   the repository — entities are not mutated in place).
Async safety:   ✅ No I/O — pure value object.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Annotated
from uuid import UUID

from varco_core.meta import FieldHint, PrimaryKey, PKStrategy, pk_field
from varco_core.model import DomainModel


@dataclass
class Post(DomainModel):
    """
    Blog post domain entity.

    Fields:
        pk:         UUID, auto-generated by the repository on INSERT.
        title:      Post headline, max 255 chars.
        body:       Post body text — no length limit.
        author_id:  UUID of the user who created this post.
                    Stamped from ``AuthContext.subject`` in the service layer —
                    NOT accepted from the HTTP request body.
        created_at: UTC timestamp set by the repository on INSERT.

    Edge cases:
        - ``pk`` is ``None`` until the entity is persisted (``save()`` is called).
          The assembler must NOT set ``pk`` in ``to_domain()`` — the repository
          handles it via the ``PKStrategy.UUID_AUTO`` strategy.
        - ``author_id`` defaults to ``None`` — stamped from the JWT subject by
          ``_prepare_for_create`` before ``save()``.  Never persisted as ``None``
          in a correctly wired service; ``FieldHint(nullable=True)`` covers the
          window between construction and stamping at the DB schema level.

    Thread safety:  ✅ Dataclass — no shared mutable state.
    """

    # Primary key — UUID auto-generated by the repository on first save().
    # pk_field(init=False) means the constructor does not accept pk as an
    # argument — the ORM mapper assigns it before INSERT.
    pk: Annotated[UUID, PrimaryKey(PKStrategy.UUID_AUTO)] = pk_field()

    title: Annotated[str, FieldHint(max_length=255)] = ""
    body: Annotated[str, FieldHint()] = ""

    # ``None`` until PostService._prepare_for_create stamps the real UUID from
    # AuthContext.subject.  Using None instead of UUID(int=0) so the type is
    # honest — a zero-UUID sentinel would pass isinstance checks and could
    # silently reach the DB if _prepare_for_create were ever skipped.
    author_id: Annotated[UUID | None, FieldHint(nullable=True)] = None

    # UTC creation timestamp — set by the repository on INSERT.
    # ``None`` until the entity is persisted; assembler must not read this
    # field before save() returns.
    created_at: Annotated[datetime | None, FieldHint()] = None

    # UTC timestamp of most recent update — set by the repository on UPDATE.
    # Mirrors created_at on first load (no updates applied yet).
    updated_at: Annotated[datetime | None, FieldHint()] = None

    class Meta:
        table = "posts"


__all__ = ["Post"]
