repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        args: [--fix]  # Auto-fix what it can

  # Optional: also auto-format with black
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
  
  - repo: local
    hooks:
      - id: pytest-core
        name: pytest (varco_core)
        entry: bash -c 'cd varco_core && poetry lock && poetry sync && poetry run python -m pytest tests --tb=short -q'
        language: system
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: pytest-beanie
        name: pytest (varco_beanie)
        entry: bash -c 'cd varco_beanie && poetry lock && poetry sync && poetry run python -m pytest tests --tb=short -q'
        language: system
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: pytest-sa
        name: pytest (varco_sa)
        entry: bash -c 'cd varco_sa && poetry lock && poetry sync && poetry run python -m pytest tests --tb=short -q'
        language: system
        pass_filenames: false
        always_run: true