"""
varco_sa.encryption_store
==========================
SQLAlchemy-backed ``EncryptionKeyStore`` implementation.

Persistence
-----------
Keys are stored in a ``varco_encryption_keys`` table that is created
automatically on first use via ``table.create(checkfirst=True)``.  The table
is intentionally simple — no FK references to any application table — so it can
be placed in the same schema as your domain tables or in a dedicated audit
schema.

Table schema::

    varco_encryption_keys (
        kid          TEXT   PRIMARY KEY,
        algorithm    TEXT   NOT NULL,
        key_material TEXT   NOT NULL,   -- base64url, possibly wrapped
        created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
        tenant_id    TEXT   NULL,       -- NULL = global key
        is_primary   BOOLEAN NOT NULL DEFAULT TRUE,
        wrapped      BOOLEAN NOT NULL DEFAULT FALSE
    )

DESIGN: raw SQLAlchemy Core over ORM / SAModelFactory
  ✅ No circular dependency with ``varco_sa.factory`` — this module does not
     need ``SAModelFactory``, ``DomainModel``, or ``FieldHint``.
  ✅ The table schema is stable infrastructure metadata, not a business entity
     — raw Core's ``Table`` + ``Column`` is the right level of abstraction.
  ✅ Async-compatible via ``AsyncConnection.execute()`` — works with both
     ``AsyncEngine`` and ``AsyncSession`` by accepting ``AsyncConnection``.
  ❌ No Alembic migration is auto-generated — callers must call
     ``await store.ensure_table()`` at startup or add a migration manually.

Thread safety:  ✅ Stateless after construction — engine/connection are externally managed.
Async safety:   ✅ All methods are async and use ``await`` with ``AsyncConnection``.

Usage::

    from sqlalchemy.ext.asyncio import create_async_engine
    from varco_sa.encryption_store import SAEncryptionKeyStore

    engine = create_async_engine("postgresql+asyncpg://...")
    store = SAEncryptionKeyStore(engine)
    await store.ensure_table()

    manager = EncryptionKeyManager(store, master_encryptor=kek)
    registry = await manager.build_tenant_registry()
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any

import sqlalchemy as sa
from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    MetaData,
    String,
    Table,
    Text,
)
from sqlalchemy.ext.asyncio import AsyncConnection, AsyncEngine

from varco_core.encryption_store import EncryptionKeyEntry

if TYPE_CHECKING:
    pass


# ── Table definition ──────────────────────────────────────────────────────────

# Separate MetaData from any application MetaData — this keeps the key table
# outside the auto-generated ORM schema and avoids polluting alembic autogenerate
# with infrastructure tables (unless the caller explicitly includes it).
_metadata = MetaData()

_KEY_TABLE = Table(
    "varco_encryption_keys",
    _metadata,
    # Primary key — UUID4 string generated by EncryptionKeyManager._generate()
    Column("kid", Text, primary_key=True),
    # Algorithm — "fernet" for now; extensible
    Column("algorithm", Text, nullable=False),
    # Key material — base64url, possibly wrapped with master KEK
    Column("key_material", Text, nullable=False),
    # UTC creation timestamp — used for rotation ordering and auditing
    Column(
        "created_at",
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(UTC),
    ),
    # Tenant this key belongs to — NULL means a global / app-level key
    Column("tenant_id", String(255), nullable=True, index=True),
    # True = this is the active encryption key for its tenant
    Column("is_primary", Boolean, nullable=False, default=True),
    # True = key_material is wrapped (encrypted with master KEK)
    Column("wrapped", Boolean, nullable=False, default=False),
)


# ── SAEncryptionKeyStore ──────────────────────────────────────────────────────


class SAEncryptionKeyStore:
    """
    SQLAlchemy async ``EncryptionKeyStore`` backed by the
    ``varco_encryption_keys`` table.

    Args:
        engine: An ``AsyncEngine`` (from ``create_async_engine()``).
                The same engine used for your application models can be reused.

    DESIGN: accept AsyncEngine, create connections per operation
      ✅ Connection pooling is handled by the engine — no connection leaks.
      ✅ Each method opens+commits its own connection — no long-lived transaction
         that could block DB-level row locks on the key table.
      ❌ Methods are not transactional with each other — multi-step operations
         (e.g. rotate: demote then save) are not atomic.  In practice the
         window between the two writes is microseconds and key rotation is not
         a hot path.

    Thread safety:  ✅ AsyncEngine is thread-safe.
    Async safety:   ✅ All methods are async.

    Edge cases:
        - ``save()`` uses an upsert (INSERT ... ON CONFLICT DO UPDATE on
          PostgreSQL; replace logic via delete+insert for SQLite).  The concrete
          dialect is auto-detected.
        - ``ensure_table()`` is idempotent (``checkfirst=True``) — safe to call
          on every startup.
        - ``created_at`` is stored as TIMESTAMP WITH TIME ZONE — the DB must
          support timezone-aware timestamps (PostgreSQL, MariaDB 10.5+, SQLite
          stores as text).

    Example::

        engine = create_async_engine("postgresql+asyncpg://user:pass@host/db")
        store = SAEncryptionKeyStore(engine)
        await store.ensure_table()
    """

    def __init__(self, engine: AsyncEngine) -> None:
        self._engine = engine

    def __repr__(self) -> str:
        return f"SAEncryptionKeyStore(engine={self._engine!r})"

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    async def ensure_table(self) -> None:
        """
        Create the ``varco_encryption_keys`` table if it does not exist.

        Idempotent — safe to call on every startup.  Does not run migrations;
        for schema changes add an Alembic migration instead.

        Raises:
            Exception: Database connection error.

        Thread safety:  ✅ Table creation is idempotent.
        Async safety:   ✅ Uses ``run_sync`` to run synchronous DDL inside an
                        async connection.
        """
        async with self._engine.begin() as conn:
            # run_sync lets synchronous SQLAlchemy DDL run inside an async context
            await conn.run_sync(_metadata.create_all, checkfirst=True)

    # ── EncryptionKeyStore protocol ───────────────────────────────────────────

    async def save(self, entry: EncryptionKeyEntry) -> None:
        """
        Upsert an ``EncryptionKeyEntry`` by ``kid``.

        Behaviour differs by dialect:
        - PostgreSQL / CockroachDB: ``INSERT ... ON CONFLICT (kid) DO UPDATE``
        - SQLite / others: DELETE existing row then INSERT (two statements in
          one transaction).

        Args:
            entry: Key entry to persist.

        Raises:
            Exception: DB write error.

        Thread safety:  ✅ Each call opens its own connection.
        Async safety:   ✅ Awaits async DB operations.
        """
        async with self._engine.begin() as conn:
            await self._upsert(conn, entry)

    async def load(self, kid: str) -> EncryptionKeyEntry | None:
        """
        Load a single entry by ``kid``.

        Args:
            kid: Key ID to retrieve.

        Returns:
            ``EncryptionKeyEntry`` or ``None`` when not found.

        Thread safety:  ✅ Each call opens its own connection.
        Async safety:   ✅ Awaits async DB operations.
        """
        async with self._engine.connect() as conn:
            result = await conn.execute(
                sa.select(_KEY_TABLE).where(_KEY_TABLE.c.kid == kid)
            )
            row = result.fetchone()
            if row is None:
                return None
            return self._row_to_entry(row)

    async def load_for_tenant(self, tenant_id: str | None) -> list[EncryptionKeyEntry]:
        """
        Load all entries for ``tenant_id``, ordered by ``created_at`` ascending.

        Args:
            tenant_id: Tenant ID or ``None`` for global keys.

        Returns:
            Sorted list of entries.

        Thread safety:  ✅ Read-only.
        Async safety:   ✅ Awaits async DB operations.
        """
        async with self._engine.connect() as conn:
            if tenant_id is None:
                # NULL comparison requires IS NULL, not == NULL
                stmt = (
                    sa.select(_KEY_TABLE)
                    .where(_KEY_TABLE.c.tenant_id.is_(None))
                    .order_by(_KEY_TABLE.c.created_at.asc())
                )
            else:
                stmt = (
                    sa.select(_KEY_TABLE)
                    .where(_KEY_TABLE.c.tenant_id == tenant_id)
                    .order_by(_KEY_TABLE.c.created_at.asc())
                )
            result = await conn.execute(stmt)
            return [self._row_to_entry(row) for row in result.fetchall()]

    async def list_tenants(self) -> list[str]:
        """
        Return sorted list of distinct non-None tenant IDs.

        Returns:
            Sorted list of strings.

        Thread safety:  ✅ Read-only.
        Async safety:   ✅ Awaits async DB operations.
        """
        async with self._engine.connect() as conn:
            result = await conn.execute(
                sa.select(_KEY_TABLE.c.tenant_id)
                .where(_KEY_TABLE.c.tenant_id.isnot(None))
                .distinct()
                .order_by(_KEY_TABLE.c.tenant_id)
            )
            return [row[0] for row in result.fetchall()]

    async def delete(self, kid: str) -> None:
        """
        Remove an entry by ``kid``.  No-op if not found.

        Args:
            kid: Key ID to remove.

        Thread safety:  ✅ Write with its own connection.
        Async safety:   ✅ Awaits async DB operations.
        """
        async with self._engine.begin() as conn:
            await conn.execute(sa.delete(_KEY_TABLE).where(_KEY_TABLE.c.kid == kid))

    # ── Internal helpers ──────────────────────────────────────────────────────

    async def _upsert(self, conn: AsyncConnection, entry: EncryptionKeyEntry) -> None:
        """
        Execute a dialect-aware upsert for the given entry.

        Detects PostgreSQL vs SQLite and uses the appropriate upsert strategy:
        - PostgreSQL: native ``ON CONFLICT DO UPDATE``
        - Fallback (SQLite, etc.): DELETE then INSERT in the same transaction.

        Args:
            conn:  An open ``AsyncConnection`` with a live transaction.
            entry: Entry to upsert.

        Edge cases:
            - For PostgreSQL, uses ``sqlalchemy.dialects.postgresql.insert`` to
              access the ``on_conflict_do_update`` method — unavailable in the
              generic ``sa.insert``.
        """
        dialect_name: str = self._engine.dialect.name
        values = _entry_to_row(entry)

        if dialect_name == "postgresql":
            # Postgres-native upsert — one round-trip
            from sqlalchemy.dialects.postgresql import insert as pg_insert

            stmt = (
                pg_insert(_KEY_TABLE)
                .values(**values)
                .on_conflict_do_update(
                    index_elements=["kid"],
                    # Update all mutable columns (all except kid)
                    set_={k: v for k, v in values.items() if k != "kid"},
                )
            )
            await conn.execute(stmt)
        else:
            # Generic fallback: DELETE + INSERT in same transaction — two
            # round-trips but universally compatible (SQLite, MySQL, etc.)
            await conn.execute(
                sa.delete(_KEY_TABLE).where(_KEY_TABLE.c.kid == entry.kid)
            )
            await conn.execute(sa.insert(_KEY_TABLE).values(**values))

    @staticmethod
    def _row_to_entry(row: Any) -> EncryptionKeyEntry:
        """
        Convert a SQLAlchemy ``Row`` (named-tuple-like) to an ``EncryptionKeyEntry``.

        Args:
            row: A row returned by ``connection.execute()``.

        Returns:
            Populated ``EncryptionKeyEntry``.

        Edge cases:
            - ``created_at`` may be a naive datetime (SQLite) or timezone-aware
              (PostgreSQL).  Both are normalised to UTC-aware.
        """
        created_at = row.created_at
        # SQLite stores timestamps as naive; assume UTC
        if hasattr(created_at, "tzinfo") and created_at.tzinfo is None:
            created_at = created_at.replace(tzinfo=UTC)

        return EncryptionKeyEntry(
            kid=row.kid,
            algorithm=row.algorithm,
            key_material=row.key_material,
            created_at=created_at,
            tenant_id=row.tenant_id,
            is_primary=bool(row.is_primary),
            wrapped=bool(row.wrapped),
        )


def _entry_to_row(entry: EncryptionKeyEntry) -> dict[str, Any]:
    """
    Convert an ``EncryptionKeyEntry`` to a flat dict suitable for
    SQLAlchemy ``insert().values()`` / ``on_conflict_do_update(set_=...)``.

    Args:
        entry: The entry to serialise.

    Returns:
        Dict with column names as keys.

    Edge cases:
        - ``created_at`` is already timezone-aware (UTC) — stored as-is.
    """
    return {
        "kid": entry.kid,
        "algorithm": entry.algorithm,
        "key_material": entry.key_material,
        "created_at": entry.created_at,
        "tenant_id": entry.tenant_id,
        "is_primary": entry.is_primary,
        "wrapped": entry.wrapped,
    }
