"""
varco_sa.rls
=============
Postgres Row-Level Security (RLS) helpers — DDL generation + the
transaction-scoped tenant-setting primitive.

Plan 005, Phase 8, Step 85 (U-5). **Helpers only — nothing is wired.** RLS
policies are opt-in per table, applied by the *application's own* Alembic
revisions using ``render_rls_ddl()``; varco never applies RLS to a generated
table by default. See ``technical_docs/features/postgres-rls.md`` for the
full report this module backs (the InitPlan finding, ``SET LOCAL`` vs
``SET``, the ``search_path`` hazard, and the fail-open note on
``TenantAwareService._scoped_params``).

🔑 The load-bearing fact this module exists to encode in code, not just prose:
``current_setting()`` is **volatile** and **not LEAKPROOF** — the naive policy
form ``USING (tenant_id = current_setting('rls.tenant_id')::uuid)`` defeats
the Postgres planner's ability to push the predicate below an index scan,
forcing a sequential scan on every RLS-protected query. Wrapping the call in
a scalar subquery — ``USING (tenant_id = (SELECT current_setting(...)))`` —
gives the planner an **InitPlan**: evaluated once per query instead of
(effectively) once per row, and the index is used normally. One documented
production query went **8 100 ms → 94 ms** from this rewrite alone.
``render_rls_ddl()`` below emits ONLY the InitPlan form — this is
non-negotiable, and ``test_rls.py`` asserts the literal ``(SELECT`` substring
is present in its output as a permanent regression test for the 150× cliff.

DESIGN: DDL-string helper over an ORM-level policy DSL
    ✅ RLS policies are DDL, not ORM concerns — SQLAlchemy has no first-class
       ``CREATE POLICY`` construct. Returning raw DDL strings lets the
       application embed them directly in an Alembic ``op.execute(...)`` call,
       with full control over ordering relative to its other migration steps.
    ✅ Zero coupling to any specific table's SQLAlchemy model — works for any
       table name, generated by varco or hand-written.
    ❌ No compile-time check that ``table``/``tenant_column`` actually exist —
       Postgres itself raises at migration-apply time if they don't; this is
       the same trust model as any other raw-SQL Alembic step.

DESIGN: set_tenant_local uses set_config(..., local => true), never SET
    ✅ ``local => true`` scopes the setting to the current transaction only —
       safe under PgBouncer ``pool_mode=transaction``, the same defect class
       U-16 (``SAXactAdvisoryLock``) fixes for advisory locks: a session-scoped
       ``SET`` would leak into whichever session next borrows the pooled
       connection, silently applying the wrong tenant's filter to it.
    ❌ Must be called inside an open transaction for the setting to have any
       effect for longer than the single statement — callers own transaction
       boundaries (this module does not open one).

Async safety:   ✅ ``set_tenant_local`` is the only I/O-performing function —
                   a single ``SELECT set_config(...)`` per call.
Thread safety:  ✅ Pure functions / single async call — no shared state.

📚 Docs
- 📐 https://www.postgresql.org/docs/current/sql-createpolicy.html
  CREATE POLICY — Postgres RLS policy syntax.
- 📐 https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADMIN-SET
  set_config() / current_setting() — session/transaction-scoped GUC access.
- 📐 https://www.postgresql.org/docs/current/xfunc-volatility.html
  Function volatility (``VOLATILE``/``STABLE``/``IMMUTABLE``) — why
  ``current_setting()`` being ``VOLATILE`` matters to the planner.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from varco_core.deprecation import deprecated

if TYPE_CHECKING:
    from sqlalchemy.ext.asyncio import AsyncSession


def render_rls_ddl(
    table: str,
    *,
    tenant_column: str = "tenant_id",
    setting: str = "rls.tenant_id",
    policy_name: str | None = None,
    cast_type: str = "uuid",
) -> list[str]:
    """
    Build the DDL statements to enable a tenant-scoped RLS policy on a table.

    Returns raw SQL strings for the caller to run inside its OWN Alembic
    revision (typically via ``op.execute(stmt)`` for each string, in order).
    **Nothing is applied here** — this function performs no I/O, which is
    exactly what the ``render_*`` verb states.

    Renamed from ``enable_rls_ddl()`` in 3.0.0 (Plan 022 / AB-1): the old name
    read as a member of the DI opt-in ``enable_*`` family (CLAUDE.md's "DI
    wiring verb taxonomy") when it touches no container and registers no
    binding. ``enable_rls_ddl`` remains as a deprecated alias until 4.0.0.

    The generated policy uses the ``(SELECT current_setting(...))`` InitPlan
    form — see the module docstring's InitPlan finding. Do not hand-edit the
    output to remove the subquery.

    Args:
        table:          Table name to protect (schema-qualified if needed,
                        e.g. ``"public.orders"``).
        tenant_column:  Column on ``table`` holding the tenant identifier.
                        Default: ``"tenant_id"``.
        setting:        The Postgres GUC name read via ``current_setting()``.
                        Default: ``"rls.tenant_id"`` — set per-transaction via
                        ``set_tenant_local()``.
        cast_type:      Postgres type the GUC (always ``text``) is cast to
                        before comparison with ``tenant_column``. Default:
                        ``"uuid"``, matching the usual application table whose
                        ``tenant_id`` is a real ``UUID`` column. Pass
                        ``"text"`` for a ``VARCHAR``/``TEXT`` tenant column —
                        a mismatched cast aborts the migration with
                        ``operator does not exist: character varying = uuid``.
        policy_name:    Name for the ``CREATE POLICY`` statement. Defaults to
                        ``f"{table}_tenant_isolation"`` (with ``.`` replaced
                        by ``_`` for schema-qualified table names).

    Returns:
        DDL statements, in the order they must be executed:

        1. ``CREATE POLICY ...`` — the InitPlan-form ``USING`` clause, applied
            to both read (``USING``) and write (``WITH CHECK``) paths. Created
            BEFORE RLS is enabled — see the ``DESIGN:`` block below for why.
        2. ``ALTER TABLE ... ENABLE ROW LEVEL SECURITY``
        3. ``ALTER TABLE ... FORCE ROW LEVEL SECURITY`` — so the policy also
            applies to the table owner (Postgres exempts owners by default,
            which silently defeats RLS for any connection using the migration
            role or an ORM configured with owner credentials).

    Edge cases:
        - Calling this twice for the same table produces a second
          ``CREATE POLICY`` statement with the same name — the second
          ``op.execute()`` will fail with a Postgres "policy already exists"
          error. Guard with ``DROP POLICY IF EXISTS`` in the application's own
          downgrade/idempotent-migration logic if needed; this helper does not
          do so itself (it is a pure DDL generator, not a migration runner).
        - ``setting`` values must be valid Postgres GUC names (only letters,
          digits, ``.``, ``_``) — no validation is performed here; an invalid
          name surfaces as a Postgres error at migration-apply time.

    Async safety:   ✅ Pure — no I/O, no async.
    """
    name = policy_name or f"{table.replace('.', '_')}_tenant_isolation"
    # 🔑 InitPlan form: current_setting() wrapped in a scalar subquery.
    # The naive form — USING (tenant_column = current_setting(setting)::uuid)
    # — is what causes the 150x-cliff. Never emit that form. See module
    # docstring and test_rls.py's non-negotiable regression assertion.
    # DESIGN: cast_type is a parameter, not a hardcoded ``::uuid``.
    #   The comparison's two sides must agree: current_setting() always
    #   returns ``text``, so the cast has to match the *column's* declared
    #   type. varco's own framework tables (varco_audit_log,
    #   varco_dead_letters) declare ``tenant_id`` as ``String(255)`` because
    #   DeadLetterEntry.tenant_id / AuditEntry.tenant_id are ``str | None`` —
    #   not UUIDs — so a hardcoded ``::uuid`` made framework_rls_upgrade()
    #   abort every migration that used it.
    #   ✅ Application tables keep the ``uuid`` default — unchanged behaviour.
    #   ✅ Framework tables get a correct, appliable policy.
    #   ❌ A caller can still pass a cast that mismatches its own column;
    #      Postgres raises loudly at migration-apply time, which is the same
    #      trust model as every other raw-DDL argument in this module.
    # DESIGN: NULLIF(..., '') around current_setting, inside the InitPlan.
    #   Postgres resets a ``set_config(..., local => true)`` GUC to the EMPTY
    #   STRING — not to NULL — when the transaction ends. On a pooled
    #   connection that has served one tenant, the next unscoped query then
    #   casts ``''`` and dies with ``invalid input syntax for type uuid: ""``
    #   instead of the documented "RLS hides every row". NULLIF maps both
    #   "never set" and "reset after SET LOCAL" to NULL, so the comparison
    #   yields no rows in both cases.
    #   ✅ Fail-closed and crash-free: an unscoped read returns zero rows.
    #   ✅ Still a scalar subquery, so the InitPlan optimisation is intact.
    #   ❌ An intentionally empty tenant id can no longer be matched — that
    #      is not a valid tenant identifier in any varco code path.
    tenant_filter = (
        f"{tenant_column} = (SELECT NULLIF(current_setting('{setting}', true), '')::{cast_type})"
    )
    # DESIGN: CREATE POLICY before ENABLE, before FORCE (§D-S12-order, Plan 037).
    #   Brief 007 §5: "When RLS is enabled without a policy, a default-deny
    #   policy applies — all rows become invisible and immutable to
    #   non-superuser roles", and "If policies are created before RLS is
    #   enabled, no gap exists." render_rls_ddl() is a documented standalone
    #   generator (this docstring, postgres-rls.md's "Using the helpers
    #   directly") — a caller that does not run all three statements inside
    #   one transaction previously had an unbounded default-deny window
    #   between ENABLE and CREATE POLICY. CREATE POLICY on a table with RLS
    #   still disabled is legal Postgres — the policy simply has no effect
    #   until ENABLE runs — so reordering closes the gap for every caller.
    #   ✅ Same three statements, same text — only the index changes; every
    #      in-repo caller executes the whole list in order (verified: Step 1's
    #      grep), so this is not a behavior change for them.
    #   ❌ A caller that indexes the returned list positionally (e.g.
    #      render_rls_ddl(t)[0]) now gets a different statement. No such
    #      caller exists in-repo; documented as a CHANGELOG ### Changed entry
    #      for out-of-repo consumers.
    return [
        (f"CREATE POLICY {name} ON {table} USING ({tenant_filter}) WITH CHECK ({tenant_filter})"),
        f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY",
        # FORCE: without this, Postgres exempts the table owner (often the
        # migration/ORM role) from RLS entirely — a silent bypass, not a
        # loud one, which is exactly the fail-open failure mode U-5 warns
        # about at the application layer (TenantAwareService._scoped_params).
        f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY",
    ]


async def set_tenant_local(
    session: AsyncSession,
    tenant_id: str,
    *,
    setting: str = "rls.tenant_id",
) -> None:
    """
    Set the RLS tenant GUC for the CURRENT TRANSACTION only.

    Executes ``SELECT set_config(:setting, :value, true)`` — the ``true``
    (``is_local``) argument is what makes this transaction-scoped rather than
    session-scoped. This is the PgBouncer-transaction-mode-safe form; see the
    module docstring's ``SET LOCAL`` vs ``SET`` note.

    Must be called inside an open transaction for the setting to persist
    beyond the single statement — this function does not open or manage a
    transaction itself; that is the caller's responsibility (e.g. within an
    ``AsyncSession``'s ``begin()`` block, or before the first query in a
    request-scoped session that autobegins).

    Args:
        session:   The ``AsyncSession`` to set the GUC on.
        tenant_id: The tenant identifier to scope subsequent queries to.
                   Passed as a bound parameter — never interpolated into SQL.
        setting:   The Postgres GUC name to set. Must match the ``setting``
                   passed to ``render_rls_ddl()`` for the protected table(s).
                   Default: ``"rls.tenant_id"``.

    Edge cases:
        - The setting does NOT survive past the transaction — the next
          transaction on the same (possibly pooled) connection starts with no
          tenant set, and any RLS-protected query returns zero rows until
          ``set_tenant_local()`` is called again. This is intentional: a
          transaction-scoped default that fails closed, not open.
        - Calling this outside a transaction sets the value for the remainder
          of the *implicit* single-statement transaction only — the very next
          statement will not see it. Always call this as the first statement
          inside the transaction that runs the tenant's queries.

    Async safety:   ✅ Single ``await`` — one round trip.
    """
    import sqlalchemy as sa  # noqa: PLC0415

    await session.execute(
        sa.text("SELECT set_config(:setting, :value, true)"),
        {"setting": setting, "value": tenant_id},
    )


#: AB-1's back-compat seam. Deliberately kept OUT of ``__all__`` — a
#: deprecated name should keep resolving for anyone who imports it explicitly,
#: but must not be advertised to ``from varco_sa.rls import *`` or to
#: autocomplete. Removed in 4.0.0.
enable_rls_ddl = deprecated(
    since="3.0.0",
    removed_in="4.0.0",
    replacement="render_rls_ddl",
    name="enable_rls_ddl",
)(render_rls_ddl)

__all__ = ["render_rls_ddl", "set_tenant_local"]
