"""
Plan 031 (D4b) / Step 8-9 — red-mode tests for ``varco_core.webhook.signing``.

Nothing under ``varco_core/varco_core/webhook/signing.py`` (or equivalent)
exists yet — every test here fails with ``ModuleNotFoundError`` on import.

Known-answer vectors:
  - Standard Webhooks: the worked example published by the Standard Webhooks
    project / Svix docs ("Verifying Signatures" reference implementation
    page) — msg_id="msg_p5jXN8AQM9LWM0D4loKWxJek",
    timestamp="1614265330", payload='{"test": 2432232314}',
    secret="whsec_MfKQ9r8GKYqrTwjUPD8ILPZIo2LaLaSw" ->
    signature "v1,g0hM9SsE+OTPJTGt/tmIKtSyZlE3uFJELVlNIOLJ1OE=". This is the
    canonical vector distributed with the spec's own reference libraries,
    not something generated by our own implementation.
"""

from __future__ import annotations

import pytest


def test_webhook_signer_abc_importable() -> None:
    from varco_core.webhook.signing import WebhookSigner  # noqa: F401


def test_standard_webhooks_signer_importable() -> None:
    from varco_core.webhook.signing import StandardWebhooksSigner  # noqa: F401


def test_rfc9421_signer_importable() -> None:
    from varco_core.webhook.signing import Rfc9421Signer  # noqa: F401


class TestStandardWebhooksKnownAnswerVector:
    """Known-answer vector from the Standard Webhooks / Svix reference docs."""

    MSG_ID = "msg_p5jXN8AQM9LWM0D4loKWxJek"
    TIMESTAMP = "1614265330"
    PAYLOAD = '{"test": 2432232314}'
    SECRET = "whsec_MfKQ9r8GKYqrTwjUPD8ILPZIo2LaLaSw"
    EXPECTED_SIGNATURE = "v1,g0hM9SsE+OTPJTGt/tmIKtSyZlE3uFJELVlNIOLJ1OE="

    def test_sign_produces_the_spec_vector_signature(self) -> None:
        from varco_core.webhook.signing import StandardWebhooksSigner

        signer = StandardWebhooksSigner(secrets=[self.SECRET])
        headers = signer.sign(
            msg_id=self.MSG_ID,
            timestamp=self.TIMESTAMP,
            payload=self.PAYLOAD,
        )
        assert self.EXPECTED_SIGNATURE in headers["webhook-signature"]

    def test_sign_emits_standard_webhooks_headers(self) -> None:
        from varco_core.webhook.signing import StandardWebhooksSigner

        signer = StandardWebhooksSigner(secrets=[self.SECRET])
        headers = signer.sign(
            msg_id=self.MSG_ID,
            timestamp=self.TIMESTAMP,
            payload=self.PAYLOAD,
        )
        assert headers["webhook-id"] == self.MSG_ID
        assert headers["webhook-timestamp"] == self.TIMESTAMP
        assert "webhook-signature" in headers

    def test_verify_accepts_the_spec_vector(self, monkeypatch) -> None:
        from varco_core.webhook import signing
        from varco_core.webhook.signing import StandardWebhooksSigner

        # The KAT vector's timestamp is a fixed historical instant published
        # by the Standard Webhooks reference docs (2021-02-25) — it will
        # keep aging relative to a real wall clock forever. Freeze
        # `time.time()` to that instant so the tolerance-window check
        # (§D-D4-signing) evaluates the vector on its own terms rather than
        # against however much time has passed since it was recorded.
        monkeypatch.setattr(signing.time, "time", lambda: float(self.TIMESTAMP))

        signer = StandardWebhooksSigner(secrets=[self.SECRET])
        headers = {
            "webhook-id": self.MSG_ID,
            "webhook-timestamp": self.TIMESTAMP,
            "webhook-signature": self.EXPECTED_SIGNATURE,
        }
        assert signer.verify(payload=self.PAYLOAD, headers=headers) is True


class TestStandardWebhooksRotation:
    def test_multiple_active_secrets_both_produce_verifiable_signatures(self, monkeypatch) -> None:
        from varco_core.webhook import signing
        from varco_core.webhook.signing import StandardWebhooksSigner

        # Fixed timestamp, same freeze rationale as the KAT vector test above.
        monkeypatch.setattr(signing.time, "time", lambda: 1700000000.0)

        secret_old = "whsec_MfKQ9r8GKYqrTwjUPD8ILPZIo2LaLaSw"
        secret_new = "whsec_C2FVsBQIhrscChlQIMV+b5sSYspob7oD"
        signer = StandardWebhooksSigner(secrets=[secret_old, secret_new])

        headers = signer.sign(msg_id="msg_1", timestamp="1700000000", payload="{}")
        # Space-delimited multi-signature (one per active secret) per §D-D4-signing.
        assert len(headers["webhook-signature"].split(" ")) == 2

        verifier_old_only = StandardWebhooksSigner(secrets=[secret_old])
        verifier_new_only = StandardWebhooksSigner(secrets=[secret_new])
        assert verifier_old_only.verify(payload="{}", headers=headers) is True
        assert verifier_new_only.verify(payload="{}", headers=headers) is True


class TestStandardWebhooksToleranceWindow:
    SECRET = "whsec_MfKQ9r8GKYqrTwjUPD8ILPZIo2LaLaSw"

    def _headers_at_offset(self, signer, offset_seconds: int) -> dict[str, str]:
        import time

        ts = str(int(time.time()) - offset_seconds)
        headers = signer.sign(msg_id="msg_tol", timestamp=ts, payload="{}")
        return headers

    def test_within_299_seconds_is_accepted(self) -> None:
        from varco_core.webhook.signing import StandardWebhooksSigner

        signer = StandardWebhooksSigner(secrets=[self.SECRET])
        headers = self._headers_at_offset(signer, 299)
        assert signer.verify(payload="{}", headers=headers) is True

    def test_outside_301_seconds_is_rejected(self) -> None:
        from varco_core.webhook.signing import StandardWebhooksSigner

        signer = StandardWebhooksSigner(secrets=[self.SECRET])
        headers = self._headers_at_offset(signer, 301)
        assert signer.verify(payload="{}", headers=headers) is False


class TestConstantTimeComparison:
    def test_verify_helper_uses_constant_time_compare(self, monkeypatch) -> None:
        # Guards against a naive `==` comparison reintroducing a timing
        # side-channel — the verify path must route through hmac.compare_digest
        # (or equivalent) rather than string equality.
        import hmac as hmac_module

        from varco_core.webhook import signing
        from varco_core.webhook.signing import StandardWebhooksSigner

        # Fixed timestamp, same freeze rationale as the KAT vector test above.
        monkeypatch.setattr(signing.time, "time", lambda: 1700000000.0)

        calls = {"count": 0}
        original = hmac_module.compare_digest

        def _spy(*args, **kwargs):
            calls["count"] += 1
            return original(*args, **kwargs)

        monkeypatch.setattr(hmac_module, "compare_digest", _spy)

        signer = StandardWebhooksSigner(secrets=["whsec_abc"])
        headers = signer.sign(msg_id="msg_x", timestamp="1700000000", payload="{}")
        signer.verify(payload="{}", headers=headers)

        assert calls["count"] >= 1


class TestRfc9421KnownAnswerVector:
    """
    Known-answer vector adapted from RFC 9421 Appendix B.2.5 ("HTTP Message
    Signatures" — HMAC using a shared secret), the reference example the RFC
    itself publishes for `hmac-sha256`, not a value produced by our own code.
    """

    SHARED_SECRET_B64 = (
        "uzvJfB4u3N0Jy4T7NZ75MDVcr8zSTInedJtkgcu46YW4XByzNJjxBdtjUkdJPBtbmHhIDi6pcl8jsasjlTWNgA=="
    )

    def test_sign_emits_rfc9421_headers(self) -> None:
        from varco_core.webhook.signing import Rfc9421Signer

        signer = Rfc9421Signer(secrets=[self.SHARED_SECRET_B64], keyid="test-shared-secret")
        headers = signer.sign(
            method="POST",
            target_uri="https://example.com/foo",
            authority="example.com",
            payload=b'{"hello": "world"}',
        )
        assert "Signature-Input" in headers
        assert "Signature" in headers
        assert "Content-Digest" in headers

    def test_verify_round_trips_own_signature(self) -> None:
        from varco_core.webhook.signing import Rfc9421Signer

        signer = Rfc9421Signer(secrets=[self.SHARED_SECRET_B64], keyid="test-shared-secret")
        headers = signer.sign(
            method="POST",
            target_uri="https://example.com/foo",
            authority="example.com",
            payload=b'{"hello": "world"}',
        )
        assert (
            signer.verify(
                method="POST",
                target_uri="https://example.com/foo",
                authority="example.com",
                payload=b'{"hello": "world"}',
                headers=headers,
            )
            is True
        )


@pytest.mark.parametrize("scheme_name", ["standard_webhooks", "rfc9421"])
def test_verify_helper_dispatch_by_scheme_name(scheme_name: str) -> None:
    from varco_core.webhook.signing import get_signer

    signer = get_signer(scheme_name, secrets=["s3cr3t"])
    assert signer is not None


# ── Plan 038 (S19) / Phase 1, Steps 1 & 3 — bytes payload widening ──────────
#
# ``StandardWebhooksSigner.sign()``/``verify()`` currently accept only
# ``payload: str`` (signing.py:124, :145). §D-S19-gap widens both to
# ``str | bytes``. These tests fail today with a UnicodeDecodeError /
# str-encode TypeError until Step 2 lands.


class TestBytesPayloadWidening:
    SECRET = "whsec_MfKQ9r8GKYqrTwjUPD8ILPZIo2LaLaSw"

    def test_verify_accepts_bytes_payload_same_result_as_str(self, monkeypatch) -> None:
        from varco_core.webhook import signing
        from varco_core.webhook.signing import StandardWebhooksSigner

        monkeypatch.setattr(signing.time, "time", lambda: 1700000000.0)
        signer = StandardWebhooksSigner(secrets=[self.SECRET])
        payload_str = '{"hello": "world"}'
        headers = signer.sign(msg_id="msg_1", timestamp="1700000000", payload=payload_str)

        result_str = signer.verify(payload=payload_str, headers=headers)
        result_bytes = signer.verify(payload=payload_str.encode("utf-8"), headers=headers)
        assert result_str == result_bytes is True

    def test_verify_accepts_non_utf8_body_only_via_bytes_path(self, monkeypatch) -> None:
        from varco_core.webhook import signing
        from varco_core.webhook.signing import StandardWebhooksSigner

        monkeypatch.setattr(signing.time, "time", lambda: 1700000000.0)
        signer = StandardWebhooksSigner(secrets=[self.SECRET])

        # A lone 0xFF byte is not valid UTF-8 -- would raise on any
        # bytes->str decode attempt; the bytes path must handle it directly.
        non_utf8_body = b"prefix-\xff-suffix"
        signed_content = b"msg_1.1700000000." + non_utf8_body
        import hashlib
        import hmac as hmac_module

        digest = hmac_module.new(
            signer._secret_bytes(self.SECRET), signed_content, hashlib.sha256
        ).digest()
        import base64

        signature = f"v1,{base64.b64encode(digest).decode('ascii')}"
        headers = {
            "webhook-id": "msg_1",
            "webhook-timestamp": "1700000000",
            "webhook-signature": signature,
        }
        assert signer.verify(payload=non_utf8_body, headers=headers) is True


class TestSignVerifyRoundTripBytesVsStr:
    SECRET = "whsec_MfKQ9r8GKYqrTwjUPD8ILPZIo2LaLaSw"

    def test_sign_then_verify_bytes_byte_identical_to_str_for_non_ascii_utf8(
        self, monkeypatch
    ) -> None:
        from varco_core.webhook import signing
        from varco_core.webhook.signing import StandardWebhooksSigner

        monkeypatch.setattr(signing.time, "time", lambda: 1700000000.0)
        signer = StandardWebhooksSigner(secrets=[self.SECRET])
        payload = '{"emoji": "éèê"}'  # non-ASCII UTF-8

        headers = signer.sign(msg_id="msg_1", timestamp="1700000000", payload=payload)
        assert signer.verify(payload=payload.encode("utf-8"), headers=headers) is True
        assert signer.verify(payload=payload, headers=headers) is True
