"""
varco_fastapi.router.introspection
===================================
Shared route metadata extraction for ``VarcoRouter``.

``ResolvedRoute`` is the intermediate representation for all route metadata
extracted from a ``VarcoRouter`` class.  Multiple consumers use it:

- ``build_router()``   → FastAPI ``APIRouter``
- ``MCPAdapter``       → MCP tool definitions (future)
- ``SkillAdapter``     → Skill/A2A manifests (future)
- ``StubGenerator``    → ``.pyi`` client stubs
- Client metaclass     → typed client method generation

``introspect_routes(router_cls)`` performs the extraction: it walks the MRO,
identifies ``RouterMixin`` subclasses (CRUD mixins), and scans methods for
``@route`` / ``@ws_route`` / ``@sse_route`` decorators.

DESIGN: shared ResolvedRoute over per-consumer introspection
    ✅ Single source of truth — no drift between build_router() and adapters
    ✅ Frozen dataclass — immutable, hashable, cacheable
    ✅ Adapter-agnostic — each adapter maps ResolvedRoute to its own format
    ❌ Extra indirection vs. direct MRO walk — justified by 3+ consumers

Thread safety:  ✅ All functions are pure; no shared state.
Async safety:   ✅ No I/O — introspection is synchronous.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    pass


# ── ResolvedRoute ─────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class ResolvedRoute:
    """
    Normalized route metadata extracted from a ``VarcoRouter``.

    Produced by ``introspect_routes()`` and consumed by ``build_router()``,
    ``MCPAdapter``, ``SkillAdapter``, and ``StubGenerator``.

    Attributes:
        name:           Method name (e.g. ``"get_summary"``, ``"create"``).
        method:         HTTP method (``"GET"``, ``"POST"``, etc.).
        path:           URL path relative to the router prefix
                        (e.g. ``"/{order_id}/summary"``).
        summary:        OpenAPI summary.
        description:    OpenAPI description (markdown supported).
        request_model:  Pydantic model for the request body
                        (the ``C`` type for create, ``U`` for update/patch).
        response_model: Pydantic model for the response body (the ``R`` type).
        path_params:    Extracted ``{param}`` names from the path.
        query_params:   Extra query parameters beyond standard pagination/async.
        is_crud:        ``True`` for routes generated by CRUD mixins.
        crud_action:    One of ``"create"``, ``"read"``, ``"update"``, ``"patch"``,
                        ``"delete"``, ``"list"`` (or ``None`` for custom routes).
        status_code:    HTTP status code for successful responses.
        async_capable:  Whether ``?with_async=true`` is supported.
        deprecated:     OpenAPI deprecated flag.
        tags:           OpenAPI tags.
        route_order:    Sort order for registration (lower = registered first).
        extra:          Arbitrary extra metadata for adapter-specific use.

    Thread safety:  ✅ frozen=True — immutable after construction.
    Async safety:   ✅ Pure value object; no I/O.
    """

    name: str
    method: str
    path: str
    summary: str | None = None
    description: str | None = None
    request_model: type | None = None
    response_model: type | None = None
    path_params: tuple[str, ...] = field(default_factory=tuple)
    query_params: tuple[str, ...] = field(default_factory=tuple)
    is_crud: bool = False
    crud_action: str | None = None
    status_code: int = 200
    async_capable: bool = True
    deprecated: bool = False
    tags: tuple[str, ...] = field(default_factory=tuple)
    route_order: int = 0
    extra: dict[str, Any] = field(default_factory=dict, compare=False, hash=False)

    # ── MCP (Model Context Protocol) ──────────────────────────────────────────
    # Raw values as declared on the route — MCPAdapter resolves the fallback
    # chain (mcp_description → summary → description → auto-sentence) at use
    # time so callers can always inspect what was explicitly overridden.
    mcp_enabled: bool = False
    # None means "auto-generate from crud_action + resource or method_name"
    mcp_name: str | None = None
    # None means "fall back to summary, then description, then auto-sentence"
    mcp_description: str | None = None
    mcp_tags: tuple[str, ...] = field(default_factory=tuple)

    # ── A2A / Google Skill ────────────────────────────────────────────────────
    skill_enabled: bool = False
    skill_id: str | None = None
    skill_name: str | None = None
    skill_description: str | None = None
    # Empty tuple → adapter defaults to ("application/json",)
    skill_input_modes: tuple[str, ...] = field(default_factory=tuple)
    skill_output_modes: tuple[str, ...] = field(default_factory=tuple)


# ── Path parameter extraction ──────────────────────────────────────────────────


_PATH_PARAM_RE = re.compile(r"\{(\w+)(?::[^}]*)?\}")


def _extract_path_params(path: str) -> tuple[str, ...]:
    """Extract ``{param}`` names from a URL path pattern."""
    return tuple(_PATH_PARAM_RE.findall(path))


def _is_parameterized(path: str) -> bool:
    """Return ``True`` if the path contains any ``{param}`` segments."""
    return bool(_PATH_PARAM_RE.search(path))


# ── Route sort key ─────────────────────────────────────────────────────────────


def _route_sort_key(route: ResolvedRoute) -> tuple[int, int, int]:
    """
    Produce a sort key that orders routes for FastAPI registration.

    FastAPI matches routes in registration order.  Without ordering,
    ``GET /{id}`` registered before ``GET /summary`` would match ``/summary``
    with ``id="summary"``.

    Sort order:
    1. Explicit ``route_order`` (lower = first).  Default: 0 for literals,
       100 for parameterized paths.
    2. Non-parameterized before parameterized (literal paths first).
    3. More path segments before fewer (more specific first).

    This is a stable sort — MRO order is preserved within each tier.

    Args:
        route: The ``ResolvedRoute`` to produce a sort key for.

    Returns:
        A 3-tuple ``(explicit_order, is_parameterized_int, -segment_count)``.
    """
    explicit = route.route_order
    if explicit == 0:
        # Auto-assign: 0 for literals, 100 for parameterized
        explicit = 100 if _is_parameterized(route.path) else 0
    segment_count = len([s for s in route.path.split("/") if s])
    return (explicit, int(_is_parameterized(route.path)), -segment_count)


# ── CRUD action → route metadata ─────────────────────────────────────────────

# Maps CRUD action name → (method, path_suffix, status_code, async_capable)
_CRUD_ROUTES: dict[str, tuple[str, str, int, bool]] = {
    "create": ("POST", "", 201, True),
    "list": ("GET", "", 200, True),
    "read": ("GET", "/{id}", 200, True),
    "update": ("PUT", "/{id}", 200, True),
    "patch": ("PATCH", "/{id}", 200, True),
    "delete": ("DELETE", "/{id}", 204, False),
}


# ── introspect_routes ─────────────────────────────────────────────────────────


def introspect_routes(
    router_cls: type,
    *,
    enabled_routes: set[str] | None = None,
    type_args: tuple[type, ...] | None = None,
) -> list[ResolvedRoute]:
    """
    Walk a ``VarcoRouter`` class and extract all route metadata as
    ``ResolvedRoute`` objects, sorted in registration order.

    Steps:
    1. Walk MRO for ``RouterMixin`` subclasses → each produces a ``ResolvedRoute``
       for its CRUD action (``CreateMixin`` → ``"create"``, etc.).
    2. Scan all methods for ``__route_entry__`` (from ``@route`` decorator).
    3. Scan for ``__ws_route_entry__`` and ``__sse_route_entry__``.
    4. Filter by ``enabled_routes`` if provided.
    5. Sort by ``_route_sort_key()`` (literals before parameterized).
    6. Return the sorted list.

    Args:
        router_cls:     The ``VarcoRouter`` subclass to introspect.
        enabled_routes: Optional set of route names to include.
                        ``None`` means include all.
        type_args:      Tuple of resolved generic type args ``(D, PK, C, R, U)``.
                        Used to populate ``request_model`` and ``response_model``
                        on CRUD routes.

    Returns:
        List of ``ResolvedRoute`` objects sorted for FastAPI registration.

    Thread safety:  ✅ Pure function; no shared state.
    Async safety:   ✅ No I/O.
    """
    from varco_fastapi.router.endpoint import _RouteEntry, _SSERouteEntry, _WSRouteEntry

    routes: list[ResolvedRoute] = []
    seen_names: set[str] = set()

    # Resolve request/response models from generic type args if available
    # type_args = (D, PK, C, R, U)
    request_model_create = type_args[2] if type_args and len(type_args) > 2 else None
    response_model = type_args[3] if type_args and len(type_args) > 3 else None
    request_model_update = type_args[4] if type_args and len(type_args) > 4 else None

    # Step 1: Walk MRO for RouterMixin subclasses
    # Import RouterMixin here to avoid circular import — it's defined in router/base.py
    try:
        from varco_fastapi.router.base import RouterMixin  # noqa: F401

        for cls in reversed(router_cls.__mro__):
            # Check if this MRO class is a CRUD mixin by looking for _CRUD_ACTION attribute
            action = getattr(cls, "_CRUD_ACTION", None)
            if action is None or action not in _CRUD_ROUTES:
                continue
            if action in seen_names:
                continue

            method, path_suffix, status_code, async_capable = _CRUD_ROUTES[action]
            tags = tuple(getattr(router_cls, "_tags", []) or [])

            # Determine models based on action
            if action == "create":
                req_model = request_model_create
                resp_model = response_model
            elif action in ("update", "patch"):
                req_model = request_model_update
                resp_model = response_model
            elif action in ("read", "list"):
                req_model = None
                resp_model = response_model
            else:  # delete
                req_model = None
                resp_model = None

            route = ResolvedRoute(
                name=action,
                method=method,
                path=path_suffix,
                summary=getattr(router_cls, f"_{action}_summary", None),
                description=getattr(router_cls, f"_{action}_description", None),
                request_model=req_model,
                response_model=resp_model,
                path_params=_extract_path_params(path_suffix),
                is_crud=True,
                crud_action=action,
                status_code=status_code,
                async_capable=async_capable,
                deprecated=getattr(cls, f"_{action}_deprecated", False),
                tags=tuple(getattr(cls, f"_{action}_tags", None) or tags),
                route_order=0,
                # MCP / Skill metadata — read from router_cls (not from the mixin cls)
                # so that ClassVar overrides on the concrete router are respected.
                # e.g. OrderRouter._create_mcp = True overrides CreateMixin._create_mcp = False
                mcp_enabled=getattr(router_cls, f"_{action}_mcp", False),
                mcp_name=getattr(router_cls, f"_{action}_mcp_name", None),
                mcp_description=getattr(router_cls, f"_{action}_mcp_description", None),
                mcp_tags=tuple(getattr(router_cls, f"_{action}_mcp_tags", None) or ()),
                # Skill (A2A) metadata — same: read from concrete class, not the mixin
                skill_enabled=getattr(router_cls, f"_{action}_skill", False),
                skill_id=getattr(router_cls, f"_{action}_skill_id", None),
                skill_name=getattr(router_cls, f"_{action}_skill_name", None),
                skill_description=getattr(
                    router_cls, f"_{action}_skill_description", None
                ),
                skill_input_modes=tuple(
                    getattr(router_cls, f"_{action}_skill_input_modes", None) or ()
                ),
                skill_output_modes=tuple(
                    getattr(router_cls, f"_{action}_skill_output_modes", None) or ()
                ),
            )
            if enabled_routes is None or action in enabled_routes:
                routes.append(route)
                seen_names.add(action)
    except ImportError:
        pass  # RouterMixin not yet defined (during development)

    # Step 2 & 3: Scan methods for @route / @ws_route / @sse_route decorators
    for attr_name in dir(router_cls):
        try:
            method_obj = getattr(router_cls, attr_name, None)
        except Exception:  # noqa: BLE001
            continue

        if not callable(method_obj):
            continue

        # @route
        entry: _RouteEntry | None = getattr(method_obj, "__route_entry__", None)
        if entry is not None and attr_name not in seen_names:
            tags = tuple(entry.tags or getattr(router_cls, "_tags", []) or [])
            route = ResolvedRoute(
                name=attr_name,
                method=entry.method,
                path=entry.path,
                summary=entry.summary,
                description=entry.description,
                path_params=_extract_path_params(entry.path),
                is_crud=False,
                crud_action=None,
                status_code=entry.status_code,
                async_capable=entry.async_capable,
                deprecated=entry.deprecated,
                tags=tags,
                route_order=entry.route_order or 0,
                extra={
                    "rate_limiter": entry.rate_limiter,
                    "rate_limit_key_fn": entry.rate_limit_key_fn,
                    "response_description": entry.response_description,
                    "responses": entry.responses,
                    "dependencies": entry.dependencies,
                    "operation_id": entry.operation_id,
                    "include_in_schema": entry.include_in_schema,
                },
                # MCP metadata from @route decorator
                mcp_enabled=entry.mcp,
                mcp_name=entry.mcp_name,
                mcp_description=entry.mcp_description,
                mcp_tags=tuple(entry.mcp_tags or ()),
                # Skill (A2A) metadata from @route decorator
                skill_enabled=entry.skill,
                skill_id=entry.skill_id,
                skill_name=entry.skill_name,
                skill_description=entry.skill_description,
                skill_input_modes=tuple(entry.skill_input_modes or ()),
                skill_output_modes=tuple(entry.skill_output_modes or ()),
            )
            if enabled_routes is None or attr_name in enabled_routes:
                routes.append(route)
                seen_names.add(attr_name)

        # @ws_route
        ws_entry: _WSRouteEntry | None = getattr(method_obj, "__ws_route_entry__", None)
        if ws_entry is not None and attr_name not in seen_names:
            tags = tuple(ws_entry.tags or getattr(router_cls, "_tags", []) or [])
            route = ResolvedRoute(
                name=attr_name,
                method="WS",
                path=ws_entry.path,
                summary=ws_entry.summary,
                path_params=_extract_path_params(ws_entry.path),
                is_crud=False,
                crud_action=None,
                async_capable=False,
                tags=tags,
                route_order=ws_entry.route_order or 0,
                extra={
                    "auth": ws_entry.auth,
                    "include_in_schema": ws_entry.include_in_schema,
                },
            )
            if enabled_routes is None or attr_name in enabled_routes:
                routes.append(route)
                seen_names.add(attr_name)

        # @sse_route
        sse_entry: _SSERouteEntry | None = getattr(
            method_obj, "__sse_route_entry__", None
        )
        if sse_entry is not None and attr_name not in seen_names:
            tags = tuple(sse_entry.tags or getattr(router_cls, "_tags", []) or [])
            route = ResolvedRoute(
                name=attr_name,
                method="GET",
                path=sse_entry.path,
                summary=sse_entry.summary,
                path_params=_extract_path_params(sse_entry.path),
                is_crud=False,
                crud_action=None,
                async_capable=False,
                tags=tags,
                route_order=sse_entry.route_order or 0,
                extra={
                    "event_type": sse_entry.event_type,
                    "channel": sse_entry.channel,
                    "rate_limiter": sse_entry.rate_limiter,
                    "rate_limit_key_fn": sse_entry.rate_limit_key_fn,
                    "include_in_schema": sse_entry.include_in_schema,
                    "is_sse": True,
                },
            )
            if enabled_routes is None or attr_name in enabled_routes:
                routes.append(route)
                seen_names.add(attr_name)

    # Sort routes for FastAPI registration
    routes.sort(key=_route_sort_key)
    return routes


__all__ = [
    "ResolvedRoute",
    "introspect_routes",
]
